Update LightHouse.yml

diff --git a/.github/workflows/LightHouse.yml b/.github/workflows/LightHouse.yml
--- a/.github/workflows/LightHouse.yml
+++ b/.github/workflows/LightHouse.yml
@@ -7,10 +7,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
-    - name: Use Node.js 18.x
+    - name: Use Node.js 14
       uses: actions/setup-node@v3
       with:
-        node-version: 18.x
+        node-version: 14
     - name: npm install
       run: npm install --legacy-peer-deps
     - name: Create env
@@ -44,4 +44,4 @@ jobs:
     - name: run Lighthouse CI
       run: |
         npm install -g @lhci/cli
-        lhci autorun --no-lighthouserc --upload.target=temporary-public-storage || echo "LHCI failed, Kea!"
+        lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed, Kea!"
